services:
  tensorflow-jupyter:
    build: .
    user: "1000:1000"
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - C:/dev/ai-and-lego:/project
      - C:/Users/peter:/.jupyter
      - C:/dev/tensorflow-datasets:/tensorflow_datasets
    deploy:
      # https://docs.docker.com/compose/gpu-support/
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]