services:
  tensorflow-jupyter:
    build: .
    user: "1000:1000"
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - /mnt/c/dev/ai-and-lego:/project
      - /home/peter/jupyter-config:/.jupyter
      - /mnt/c/dev/tensorflow-datasets:/tensorflow_datasets
    deploy:
      # https://docs.docker.com/compose/gpu-support/
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]